<script>
  let { onNav = () => {}, onGoToApp = () => {} } = $props();
</script>

<section class="gp-hero"><div class="gp-wrap">
  <p class="gp-badge"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 17.5V21h3.5l11-11-3.5-3.5-11 11z"/><path d="M14 6.5 17.5 10"/><path d="M3 21h18"/></svg> E-Kontrak Digital</p>
  <h1 class="gp-h1">Kontrak Jamaah Jadi <em>Lebih Profesional dan Tertelusur</em></h1>
  <p class="gp-lead">Buat akad sekali sebagai template, lalu kirim ke jamaah untuk ditandatangani langsung dari ponsel — tanpa cetak, tanpa install aplikasi, dan tersimpan aman selamanya.</p>
  <div class="gp-cta-row"><button class="gp-btn gp-btn-primary" type="button" onclick={() => onGoToApp()}>Coba Gratis 14 Hari</button><button class="gp-btn gp-btn-ghost" type="button" onclick={() => onNav('software')}>Lihat Platform Lengkap</button></div>
  <p class="gp-meta"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg> Terakhir diperbarui: 8 Juni 2026</p>
</div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Masalah</div><h2 class="gp-h2">Kontrak Kertas Rentan Hilang dan Sulit Diaudit</h2><div class="gp-prose"><p>Akad umrah yang dicetak dan ditandatangani basah sering tercecer, sulit dicari saat dibutuhkan, dan tidak punya jejak kapan serta oleh siapa ditandatangani.</p><p>Mengetik ulang nama, paket, dan nominal untuk setiap jamaah juga membuang waktu dan berisiko salah.</p><p>E-Kontrak Suluk membuat seluruh proses menjadi digital, otomatis, dan tertelusur.</p></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Solusi</div><h2 class="gp-h2">Template Pintar &amp; Tanda Tangan dari Ponsel</h2><ul class="gp-benefits"><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Template dengan variabel —</b> nama, paket, dan nominal terisi otomatis dari data jamaah.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Link tanda tangan —</b> kirim tautan via WhatsApp; jamaah tanda tangan di ponsel.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Tanpa install aplikasi —</b> jamaah cukup buka tautan di browser.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>PDF immutable —</b> dokumen final terkunci dan tersimpan aman.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Audit trail —</b> jejak lengkap kapan kontrak dikirim, dibuka, dan ditandatangani.</span></li></ul></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Cara Kerja</div><h2 class="gp-h2">E-Kontrak dalam 3 Langkah</h2><div class="gp-steps"><div class="gp-step"><div class="num">1</div><h3>Buat template</h3><p>Susun akad sekali dengan variabel otomatis.</p></div><div class="gp-step"><div class="num">2</div><h3>Kirim ke jamaah</h3><p>Bagikan tautan tanda tangan via WhatsApp.</p></div><div class="gp-step"><div class="num">3</div><h3>Tersimpan &amp; terlacak</h3><p>Jamaah tanda tangan, PDF final tersimpan dengan audit trail.</p></div></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Fitur Utama</div><h2 class="gp-h2">Fitur E-Kontrak Suluk</h2><div class="gp-caps"><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 17.5V21h3.5l11-11-3.5-3.5-11 11z"/><path d="M14 6.5 17.5 10"/><path d="M3 21h18"/></svg></div><h3>Signature Pad</h3><p>Jamaah menandatangani langsung di layar ponsel.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></svg></div><h3>PDF Immutable</h3><p>Dokumen final tidak bisa diubah dan aman secara hukum.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg></div><h3>Variabel Otomatis</h3><p>Data jamaah mengisi kontrak tanpa ketik ulang.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg></div><h3>Tracking Status</h3><p>Pantau kontrak yang masih menunggu tanda tangan.</p></div></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">FAQ</div><h2 class="gp-h2">Pertanyaan Umum</h2><div class="gp-faq"><details><summary>Apakah tanda tangan digital sah secara hukum?</summary><div class="ans">Tanda tangan elektronik diakui dalam UU ITE di Indonesia. Suluk menyimpan audit trail lengkap sebagai bukti keabsahan.</div></details><details><summary>Apakah jamaah perlu aplikasi khusus?</summary><div class="ans">Tidak. Jamaah cukup membuka tautan di browser ponsel dan menandatangani di layar.</div></details><details><summary>Di mana kontrak tersimpan?</summary><div class="ans">Setiap kontrak final disimpan sebagai PDF immutable yang bisa diunduh kapan saja oleh travel.</div></details></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Pelajari Juga</div><h2 class="gp-h2">Modul Terkait</h2><div class="gp-related"><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('fitur-crm')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg></div><h4>CRM Jamaah</h4><p>Kirim kontrak begitu jamaah closing di pipeline.</p><span class="more">Selengkapnya →</span></button><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('fitur-invoice')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="9" y1="13" x2="15" y2="13"/><line x1="9" y1="17" x2="13" y2="17"/></svg></div><h4>Invoice Otomatis</h4><p>Tagihan &amp; kontrak dalam satu alur pendaftaran.</p><span class="more">Selengkapnya →</span></button><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('software')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22" x2="12" y2="12"/></svg></div><h4>Platform Lengkap</h4><p>12 modul operasional travel dalam satu sistem.</p><span class="more">Selengkapnya →</span></button></div></div></section>
<section class="gp-cta"><div class="gp-wrap"><div class="gp-cta-box"><h2>Profesionalkan Akad Jamaah Anda</h2><p>Coba E-Kontrak digital gratis 14 hari dan tinggalkan kontrak kertas yang merepotkan.</p><button class="gp-btn" type="button" onclick={() => onGoToApp()}>Mulai Trial 14 Hari Gratis →</button></div></div></section>
