<script>
  let { onNav = () => {}, onGoToApp = () => {} } = $props();
</script>

<section class="gp-hero"><div class="gp-wrap">
  <p class="gp-badge"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/></svg> Laporan Keuangan Real-Time</p>
  <h1 class="gp-h1">Tahu Profit Setiap Trip <em>Tanpa Harus Hitung Manual</em></h1>
  <p class="gp-lead">Laba rugi per keberangkatan terhitung otomatis dari invoice dan pengeluaran vendor. Pantau profit, piutang, dan arus kas kapan saja dari satu dashboard.</p>
  <div class="gp-cta-row"><button class="gp-btn gp-btn-primary" type="button" onclick={() => onGoToApp()}>Coba Gratis 14 Hari</button><button class="gp-btn gp-btn-ghost" type="button" onclick={() => onNav('software')}>Lihat Platform Lengkap</button></div>
  <p class="gp-meta"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg> Terakhir diperbarui: 8 Juni 2026</p>
</div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Masalah</div><h2 class="gp-h2">P&amp;L Dihitung Manual Setelah Trip Selesai</h2><div class="gp-prose"><p>Banyak travel baru tahu untung-rugi sebuah trip berminggu-minggu setelah pulang, ketika semua nota vendor dan pembayaran jamaah akhirnya direkap manual di Excel.</p><p>Tanpa angka real-time, sulit mengetahui paket mana yang paling menguntungkan, berapa piutang yang menggantung, atau apakah arus kas cukup untuk membayar vendor.</p><p>Modul Keuangan Suluk menghasilkan laporan otomatis dari transaksi yang sudah Anda catat di modul lain.</p></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Solusi</div><h2 class="gp-h2">Laporan Otomatis dari Data yang Sudah Ada</h2><ul class="gp-benefits"><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>P&amp;L per trip —</b> laba rugi setiap keberangkatan dihitung otomatis dan real-time.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Piutang aging —</b> laporan tunggakan jamaah berdasarkan umur jatuh tempo.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Arus kas —</b> proyeksi pemasukan dan pengeluaran untuk perencanaan.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Margin per paket —</b> bandingkan profitabilitas antar paket umrah dan haji.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Dashboard owner —</b> gross profit, total piutang, dan kas dalam satu layar.</span></li></ul></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Cara Kerja</div><h2 class="gp-h2">Laporan dalam 3 Langkah</h2><div class="gp-steps"><div class="gp-step"><div class="num">1</div><h3>Catat transaksi</h3><p>Invoice jamaah dan pengeluaran vendor tercatat di modul masing-masing.</p></div><div class="gp-step"><div class="num">2</div><h3>Sistem mengolah</h3><p>Suluk mengakumulasi data menjadi laporan keuangan otomatis.</p></div><div class="gp-step"><div class="num">3</div><h3>Pantau dashboard</h3><p>Lihat P&amp;L, piutang, dan arus kas kapan saja, di mana saja.</p></div></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Fitur Utama</div><h2 class="gp-h2">Laporan Setara Software Akuntansi</h2><div class="gp-caps"><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/></svg></div><h3>P&amp;L Dashboard</h3><p>Laba rugi per trip dan keseluruhan, real-time.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg></div><h3>Piutang Aging</h3><p>Tunggakan jamaah dikelompokkan berdasarkan jatuh tempo.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 7V5a2 2 0 0 0-2-2H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-3a2 2 0 0 1 0-4h4"/><path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"/></svg></div><h3>Arus Kas</h3><p>Proyeksi pemasukan dan pengeluaran travel.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22" x2="12" y2="12"/></svg></div><h3>Margin per Paket</h3><p>Ketahui paket paling menguntungkan untuk strategi harga.</p></div></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">FAQ</div><h2 class="gp-h2">Pertanyaan Umum</h2><div class="gp-faq"><details><summary>Apakah perlu latar belakang akuntansi?</summary><div class="ans">Tidak. Laporan disajikan dengan istilah yang mudah dipahami pemilik travel, bukan jurnal akuntansi yang rumit.</div></details><details><summary>Dari mana data laporan berasal?</summary><div class="ans">Otomatis dari modul Invoice (pemasukan) dan Vendor (pengeluaran), sehingga tidak perlu input ganda.</div></details><details><summary>Bisakah diekspor?</summary><div class="ans">Ya, laporan dapat diunduh dalam format PDF dan Excel untuk keperluan internal maupun audit.</div></details></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Pelajari Juga</div><h2 class="gp-h2">Modul Terkait</h2><div class="gp-related"><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('fitur-invoice')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="9" y1="13" x2="15" y2="13"/><line x1="9" y1="17" x2="13" y2="17"/></svg></div><h4>Invoice Otomatis</h4><p>Sumber data pemasukan untuk laporan keuangan.</p><span class="more">Selengkapnya →</span></button><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('fitur-payroll')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 7V5a2 2 0 0 0-2-2H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-3a2 2 0 0 1 0-4h4"/><path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"/></svg></div><h4>Payroll</h4><p>Gaji &amp; honor muthawwif masuk ke biaya operasional.</p><span class="more">Selengkapnya →</span></button><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('software')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22" x2="12" y2="12"/></svg></div><h4>Platform Lengkap</h4><p>12 modul operasional travel dalam satu sistem.</p><span class="more">Selengkapnya →</span></button></div></div></section>
<section class="gp-cta"><div class="gp-wrap"><div class="gp-cta-box"><h2>Lihat Profit Travel Anda Hari Ini</h2><p>Coba modul Keuangan gratis 14 hari dan pantau kesehatan finansial travel Anda real-time.</p><button class="gp-btn" type="button" onclick={() => onGoToApp()}>Mulai Trial 14 Hari Gratis →</button></div></div></section>
