<script>
  let { onNav = () => {}, onGoToApp = () => {} } = $props();
</script>

<section class="gp-hero"><div class="gp-wrap">
  <p class="gp-badge"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 7V5a2 2 0 0 0-2-2H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-3a2 2 0 0 1 0-4h4"/><path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"/></svg> Penggajian & Payroll</p>
  <h1 class="gp-h1">Gaji Karyawan & Honor Muthawwif <em>Terhitung Otomatis</em></h1>
  <p class="gp-lead">Hitung gaji karyawan tetap dan honor muthawwif freelance per trip, lengkap dengan PPh 21, BPJS, dan kasbon — lalu hasilkan slip gaji serta rekap transfer bank dalam sekali klik.</p>
  <div class="gp-cta-row"><button class="gp-btn gp-btn-primary" type="button" onclick={() => onGoToApp()}>Coba Gratis 14 Hari</button><button class="gp-btn gp-btn-ghost" type="button" onclick={() => onNav('software')}>Lihat Platform Lengkap</button></div>
  <p class="gp-meta"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg> Terakhir diperbarui: 8 Juni 2026</p>
</div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Masalah</div><h2 class="gp-h2">Hitung Gaji Manual, Tanpa Slip Formal</h2><div class="gp-prose"><p>Travel umrah punya struktur penggajian unik: karyawan tetap bulanan plus muthawwif freelance yang dibayar per trip. Menghitungnya manual setiap bulan melelahkan dan rawan salah.</p><p>Tanpa slip gaji formal, karyawan sulit mengurus keperluan administrasi, dan travel kesulitan melaporkan PPh 21 serta iuran BPJS dengan benar.</p><p>Modul Payroll Suluk mengotomatiskan seluruh perhitungan ini.</p></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Solusi</div><h2 class="gp-h2">Payroll Lengkap untuk Travel &amp; Muthawwif</h2><ul class="gp-benefits"><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Slip gaji otomatis —</b> dihasilkan rapi untuk setiap karyawan tiap periode.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Honor muthawwif per trip —</b> hitung honor freelance berdasarkan keberangkatan.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>PPh 21 &amp; BPJS —</b> potongan pajak dan iuran dihitung otomatis.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Kasbon karyawan —</b> catat dan potong kasbon dari gaji secara otomatis.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Rekap transfer bank —</b> daftar transfer siap pakai untuk pembayaran massal.</span></li></ul></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Cara Kerja</div><h2 class="gp-h2">Penggajian dalam 3 Langkah</h2><div class="gp-steps"><div class="gp-step"><div class="num">1</div><h3>Atur data karyawan</h3><p>Tetapkan gaji pokok, tunjangan, dan status karyawan/muthawwif.</p></div><div class="gp-step"><div class="num">2</div><h3>Proses periode</h3><p>Sistem menghitung gaji, potongan, dan honor trip otomatis.</p></div><div class="gp-step"><div class="num">3</div><h3>Terbitkan slip</h3><p>Slip gaji dan rekap transfer langsung siap dibagikan.</p></div></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Fitur Utama</div><h2 class="gp-h2">Fitur Payroll Travel Umrah</h2><div class="gp-caps"><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 7V5a2 2 0 0 0-2-2H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-3a2 2 0 0 1 0-4h4"/><path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"/></svg></div><h3>Slip Gaji</h3><p>Slip resmi otomatis untuk setiap karyawan.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg></div><h3>Honor Muthawwif</h3><p>Perhitungan honor freelance per keberangkatan.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/></svg></div><h3>PPh 21 &amp; BPJS</h3><p>Pajak dan iuran terhitung sesuai ketentuan.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="6" width="20" height="12" rx="2"/><circle cx="12" cy="12" r="2"/><path d="M6 12h.01"/><path d="M18 12h.01"/></svg></div><h3>Rekap Transfer</h3><p>Daftar transfer bank siap pakai untuk gajian.</p></div></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">FAQ</div><h2 class="gp-h2">Pertanyaan Umum</h2><div class="gp-faq"><details><summary>Apakah bisa untuk muthawwif freelance?</summary><div class="ans">Ya. Suluk mendukung honor per trip untuk muthawwif freelance, terpisah dari gaji bulanan karyawan tetap.</div></details><details><summary>Apakah PPh 21 dihitung otomatis?</summary><div class="ans">Ya, potongan PPh 21 dan iuran BPJS dihitung otomatis dan tampil di slip gaji.</div></details><details><summary>Bagaimana proses pembayarannya?</summary><div class="ans">Suluk menghasilkan rekap transfer yang bisa langsung digunakan untuk pembayaran massal melalui bank.</div></details></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Pelajari Juga</div><h2 class="gp-h2">Modul Terkait</h2><div class="gp-related"><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('fitur-keuangan')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/></svg></div><h4>Laporan Keuangan</h4><p>Biaya gaji otomatis masuk ke P&amp;L travel.</p><span class="more">Selengkapnya →</span></button><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('software')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22" x2="12" y2="12"/></svg></div><h4>Platform Lengkap</h4><p>12 modul operasional travel dalam satu sistem.</p><span class="more">Selengkapnya →</span></button><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('fitur-crm')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg></div><h4>CRM Jamaah</h4><p>Kelola jamaah dari prospek hingga berangkat.</p><span class="more">Selengkapnya →</span></button></div></div></section>
<section class="gp-cta"><div class="gp-wrap"><div class="gp-cta-box"><h2>Sederhanakan Penggajian Travel Anda</h2><p>Coba modul Payroll gratis 14 hari dan akhiri perhitungan gaji manual yang melelahkan.</p><button class="gp-btn" type="button" onclick={() => onGoToApp()}>Mulai Trial 14 Hari Gratis →</button></div></div></section>
