<script>
  let { onNav = () => {}, onGoToApp = () => {} } = $props();
</script>

<section class="gp-hero"><div class="gp-wrap">
  <p class="gp-badge"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg> CRM & Pipeline Jamaah</p>
  <h1 class="gp-h1">Database Jamaah Terintegrasi, <em>Repeat Order Lebih Mudah</em></h1>
  <p class="gp-lead">Lihat seluruh perjalanan setiap calon jamaah dalam satu pipeline visual — dari prospek pertama hingga keberangkatan — dan jaga hubungan untuk umrah berikutnya.</p>
  <div class="gp-cta-row"><button class="gp-btn gp-btn-primary" type="button" onclick={() => onGoToApp()}>Coba Gratis 14 Hari</button><button class="gp-btn gp-btn-ghost" type="button" onclick={() => onNav('software')}>Lihat Platform Lengkap</button></div>
  <p class="gp-meta"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg> Terakhir diperbarui: 8 Juni 2026</p>
</div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Masalah</div><h2 class="gp-h2">Data Prospek Tersebar, Histori Jamaah Hilang</h2><div class="gp-prose"><p>Lead datang dari Instagram, WhatsApp, referral, dan pameran — lalu tercatat di tempat berbeda-beda. Tim marketing sulit tahu mana prospek yang perlu di-follow up hari ini.</p><p>Setelah jamaah berangkat, datanya pun sering hilang di tumpukan file lama. Padahal jamaah lama adalah sumber repeat order dan referral terbaik untuk travel umrah.</p><p>CRM Suluk menyatukan semua prospek dan jamaah dalam satu pipeline, lengkap dengan riwayat lintas tahun.</p></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Solusi</div><h2 class="gp-h2">Pipeline Visual &amp; Database Terpusat</h2><ul class="gp-benefits"><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Pipeline kanban —</b> seret kartu lead antar tahap: prospek, follow up, negosiasi, hingga closing.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Segmentasi jamaah —</b> kelompokkan berdasarkan paket, kota, atau sumber lead.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Alert follow-up —</b> pengingat otomatis agar tidak ada prospek yang terlewat.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Database historis —</b> lihat riwayat keberangkatan jamaah lintas tahun untuk repeat order.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Integrasi WhatsApp —</b> hubungi prospek langsung tanpa pindah aplikasi.</span></li></ul></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Cara Kerja</div><h2 class="gp-h2">Kelola Prospek dalam 3 Langkah</h2><div class="gp-steps"><div class="gp-step"><div class="num">1</div><h3>Input lead</h3><p>Tambahkan prospek dari iklan, WA, atau pendaftaran online.</p></div><div class="gp-step"><div class="num">2</div><h3>Lacak pipeline</h3><p>Pindahkan kartu antar tahap sesuai progres penjualan.</p></div><div class="gp-step"><div class="num">3</div><h3>Konversi</h3><p>Ubah prospek menjadi jamaah terdaftar dan invoice otomatis.</p></div></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Fitur Utama</div><h2 class="gp-h2">Fitur CRM Travel Umrah</h2><div class="gp-caps"><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg></div><h3>Kanban Pipeline</h3><p>Visualisasi tahap penjualan yang mudah dipahami tim.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"/></svg></div><h3>Alert Follow-Up</h3><p>Pengingat otomatis untuk prospek yang perlu dihubungi.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22" x2="12" y2="12"/></svg></div><h3>Database Historis</h3><p>Riwayat jamaah lintas tahun untuk repeat order &amp; referral.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="9" y1="13" x2="15" y2="13"/><line x1="9" y1="17" x2="13" y2="17"/></svg></div><h3>Konversi ke Invoice</h3><p>Sekali closing, langsung jadi jamaah dengan tagihan otomatis.</p></div></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">FAQ</div><h2 class="gp-h2">Pertanyaan Umum</h2><div class="gp-faq"><details><summary>Apakah CRM terhubung ke modul lain?</summary><div class="ans">Ya. Prospek yang closing otomatis menjadi data jamaah, dan tagihannya langsung dibuat di modul Invoice.</div></details><details><summary>Bisakah melacak sumber lead?</summary><div class="ans">Bisa. Setiap lead bisa diberi label sumber (Instagram, WA, referral, pameran) untuk analisis efektivitas marketing.</div></details><details><summary>Apakah data jamaah lama tersimpan?</summary><div class="ans">Ya, seluruh riwayat keberangkatan tersimpan permanen sehingga mudah menawarkan paket baru ke jamaah lama.</div></details></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Pelajari Juga</div><h2 class="gp-h2">Modul Terkait</h2><div class="gp-related"><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('fitur-invoice')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="9" y1="13" x2="15" y2="13"/><line x1="9" y1="17" x2="13" y2="17"/></svg></div><h4>Invoice Otomatis</h4><p>Tagihan otomatis begitu prospek closing.</p><span class="more">Selengkapnya →</span></button><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('fitur-kontrak')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 17.5V21h3.5l11-11-3.5-3.5-11 11z"/><path d="M14 6.5 17.5 10"/><path d="M3 21h18"/></svg></div><h4>E-Kontrak Digital</h4><p>Akad ditandatangani jamaah dari ponsel.</p><span class="more">Selengkapnya →</span></button><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('software')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22" x2="12" y2="12"/></svg></div><h4>Platform Lengkap</h4><p>12 modul operasional travel dalam satu sistem.</p><span class="more">Selengkapnya →</span></button></div></div></section>
<section class="gp-cta"><div class="gp-wrap"><div class="gp-cta-box"><h2>Jangan Biarkan Prospek Terlewat</h2><p>Coba CRM Suluk gratis 14 hari dan kelola seluruh pipeline jamaah Anda di satu tempat.</p><button class="gp-btn" type="button" onclick={() => onGoToApp()}>Mulai Trial 14 Hari Gratis →</button></div></div></section>
