<script>
  let { onNav = () => {}, onGoToApp = () => {} } = $props();
</script>

<section class="gp-hero"><div class="gp-wrap">
  <p class="gp-badge"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="9" y1="13" x2="15" y2="13"/><line x1="9" y1="17" x2="13" y2="17"/></svg> Invoice & Pembayaran Otomatis</p>
  <h1 class="gp-h1">Invoice Per Jamaah Jadi <em>Lebih Cepat dan Akurat</em></h1>
  <p class="gp-lead">Buat tagihan jamaah dalam dua menit, atur cicilan sesuai kesepakatan, dan pantau siapa yang belum lunas — semua otomatis tanpa rekap manual di Excel.</p>
  <div class="gp-cta-row"><button class="gp-btn gp-btn-primary" type="button" onclick={() => onGoToApp()}>Coba Gratis 14 Hari</button><button class="gp-btn gp-btn-ghost" type="button" onclick={() => onNav('software')}>Lihat Platform Lengkap</button></div>
  <p class="gp-meta"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg> Terakhir diperbarui: 8 Juni 2026</p>
</div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Masalah</div><h2 class="gp-h2">Invoice Manual Rawan Error dan Piutang Tak Terpantau</h2><div class="gp-prose"><p>Membuat kwitansi satu per satu di Word atau Excel memakan waktu dan mudah salah ketik nominal. Ketika jamaah mencicil, catatan pembayaran tersebar di buku, chat, dan mutasi rekening.</p><p>Akibatnya travel sering tidak tahu persis berapa total piutang yang belum tertagih, dan jamaah yang menunggak baru ketahuan menjelang keberangkatan — saat sudah terlambat.</p><p>Modul Invoice Suluk membuat seluruh siklus tagihan menjadi otomatis dan transparan, dari penerbitan hingga pelunasan.</p></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Solusi</div><h2 class="gp-h2">Tagihan Otomatis, Cicilan Fleksibel, Piutang Terpantau</h2><ul class="gp-benefits"><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Auto-generate invoice —</b> tagihan dibuat otomatis dari paket dan tier harga yang dipilih jamaah.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Skema cicilan fleksibel —</b> atur DP dan termin cicilan sesuai kesepakatan dengan jamaah.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Rekam pembayaran —</b> catat setiap pembayaran beserta metode dan tanggalnya.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Kwitansi PDF —</b> cetak atau kirim kwitansi profesional langsung ke jamaah.</span></li><li><span class="ck"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></span><span><b>Laporan piutang (aging) —</b> lihat tunggakan yang jatuh tempo agar bisa ditindaklanjuti tepat waktu.</span></li></ul></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Cara Kerja</div><h2 class="gp-h2">Buat Invoice dalam 3 Langkah</h2><div class="gp-steps"><div class="gp-step"><div class="num">1</div><h3>Pilih paket</h3><p>Tentukan paket dan tier harga jamaah.</p></div><div class="gp-step"><div class="num">2</div><h3>Pilih jamaah</h3><p>Pilih jamaah dari database; data tagihan terisi otomatis.</p></div><div class="gp-step"><div class="num">3</div><h3>Invoice terbuat</h3><p>Tagihan dan jadwal cicilan langsung dibuat dan siap dikirim.</p></div></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Fitur Utama</div><h2 class="gp-h2">Semua Kebutuhan Penagihan</h2><div class="gp-caps"><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="9" y1="13" x2="15" y2="13"/><line x1="9" y1="17" x2="13" y2="17"/></svg></div><h3>Invoice Otomatis</h3><p>Tagihan dibuat dari paket tanpa input ulang data jamaah.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 7V5a2 2 0 0 0-2-2H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-3a2 2 0 0 1 0-4h4"/><path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"/></svg></div><h3>Multi-Cicilan</h3><p>Atur beberapa termin pembayaran dalam satu invoice.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></svg></div><h3>Kwitansi PDF</h3><p>Bukti pembayaran rapi dan profesional untuk jamaah.</p></div><div class="gp-cap"><div class="ic"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg></div><h3>Piutang Aging</h3><p>Pantau tunggakan berdasarkan jatuh tempo secara otomatis.</p></div></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">FAQ</div><h2 class="gp-h2">Pertanyaan Umum</h2><div class="gp-faq"><details><summary>Apakah bisa integrasi dengan bank?</summary><div class="ans">Anda dapat mencatat pembayaran dari metode apa pun (transfer, tunai, virtual account). Rekonsiliasi otomatis dengan bank tersedia di paket Business.</div></details><details><summary>Apa bedanya dengan invoice manual?</summary><div class="ans">Invoice Suluk terhubung langsung ke data jamaah dan paket, jadi tidak ada salah ketik, dan status pembayaran serta piutang terpantau otomatis di dashboard.</div></details><details><summary>Bisakah jamaah melihat tagihannya?</summary><div class="ans">Ya, Anda bisa mengirimkan invoice dan kwitansi ke jamaah melalui tautan atau WhatsApp.</div></details></div></div></section>
<section class="gp-sec"><div class="gp-wrap"><div class="gp-eyebrow">Pelajari Juga</div><h2 class="gp-h2">Modul Terkait</h2><div class="gp-related"><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('fitur-keuangan')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/></svg></div><h4>Laporan Keuangan</h4><p>Lihat profit per trip dari data invoice &amp; pengeluaran.</p><span class="more">Selengkapnya →</span></button><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('fitur-crm')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg></div><h4>CRM Jamaah</h4><p>Lacak status jamaah dari prospek hingga lunas.</p><span class="more">Selengkapnya →</span></button><button class="gp-rel" type="button" style="cursor:pointer;text-align:left;width:100%" onclick={() => onNav('software')}><div class="ic"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22" x2="12" y2="12"/></svg></div><h4>Platform Lengkap</h4><p>12 modul operasional travel dalam satu sistem.</p><span class="more">Selengkapnya →</span></button></div></div></section>
<section class="gp-cta"><div class="gp-wrap"><div class="gp-cta-box"><h2>Hemat Waktu Penagihan Anda</h2><p>Coba modul Invoice gratis 14 hari dan lihat sendiri betapa cepatnya menagih jamaah.</p><button class="gp-btn" type="button" onclick={() => onGoToApp()}>Mulai Trial 14 Hari Gratis →</button></div></div></section>
