"""add version column for optimistic locking

Revision ID: 6b58c0cb7608
Revises: a98c665d8b23
Create Date: 2026-02-26 20:22:41.326287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b58c0cb7608'
down_revision: Union[str, Sequence[str], None] = 'a98c665d8b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_group_members_family_id'), 'group_members', ['family_id'], unique=False)
    op.add_column('groups', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.drop_constraint(op.f('groups_shared_token_key'), 'groups', type_='unique')
    op.drop_index(op.f('ix_groups_shared_token'), table_name='groups')
    op.create_index(op.f('ix_groups_shared_token'), 'groups', ['shared_token'], unique=True)
    op.drop_constraint(op.f('payments_order_id_key'), 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('payments_order_id_key'), 'payments', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_groups_shared_token'), table_name='groups')
    op.create_index(op.f('ix_groups_shared_token'), 'groups', ['shared_token'], unique=False)
    op.create_unique_constraint(op.f('groups_shared_token_key'), 'groups', ['shared_token'], postgresql_nulls_not_distinct=False)
    op.drop_column('groups', 'version')
    op.drop_index(op.f('ix_group_members_family_id'), table_name='group_members')
    # ### end Alembic commands ###
